spring:
  jpa:
    open-in-view: false
  redis:
    host: 127.0.0.1
    port: 6379

jwt:
  access-token-header: AccessToken
  refresh-token-header: RefreshToken
  issuer: waterfogsw
  prefix: bearer
  client-secret: ${jwt.token-secret}
  access-token-expiry-seconds: 1800000
  refresh-token-expiry-seconds: 1209600000
